// reddit workflow definitions
// 目标站点：WebArena reddit（Postmill-based Reddit 克隆）
// 任务语料：129 条，来自 WebArena test.raw.json reddit 站点任务

export default [
  {
    id: "cross-site-post",
    kind: "domain",
    title: "跨站内容引用并发帖",
    keywords: "gitlab, repo, OneStopShop, gimmiethat.space, shopping, promote, link to",
    modelTerms: ["cross-site", "external", "link", "repo", "gitlab"],
    task: /gitlab|gimmiethat\.space|OneStopShop|byteblaze|koush|auth0|lahwaacz|promote\s+\w+\/\w+|create.*folder.*\brepo\b|make.*folder.*\brepo\b|create\s+a\s+repository\s+named|make\s+a\s+(?:folder|repository)\s+named.*\brepo\b|gitlabΨ/i,
    evidence: /gitlab|github|repo|repository|external|link|url|跨站|仓库/i,
    coverage: /gitlab|repo|repository|external|link/i,
    steps: [
      "确认任务要求的外部来源（GitLab 仓库/购物网站评论/指定页面）。",
      "打开外部站点，提取任务要求的内容（URL、描述、评论标题等）。",
      "切换到 reddit，找到任务指定的或最合适的 subreddit。",
      "创建帖子，粘贴从外部收集的内容，提交。",
      "确认帖子已成功发布。",
    ],
    success: [
      "帖子内容准确引用了外部来源的数据。",
      "帖子发布在任务指定或最匹配的 subreddit。",
    ],
    checks: [
      "提取外部数据时记录原始值，避免复制错误。",
      "GitLab 描述从仓库主页 About 区域读取，不要自行编写。",
      "跨站任务顺序：先采集，再发帖；不要同时打开多个标签混淆状态。",
    ],
    risk: "这是写操作，发帖后不可直接撤回；发帖前必须核对内容与来源一致。",
  },
  {
    id: "forum-create",
    kind: "domain",
    title: "创建新论坛（Subreddit）",
    keywords: "create forum, new subreddit, sidebar, description",
    modelTerms: ["forum", "subreddit", "create"],
    task: /create\s+(?:a\s+)?(?:new\s+)?forum\s+named|create\s+(?:a\s+)?(?:new\s+)?subreddit\s+named/i,
    evidence: /forum|subreddit|create|sidebar|description|论坛|创建/i,
    coverage: /forum|subreddit|create/i,
    steps: [
      "进入 reddit 首页，找到「Create a Forum」或「Create Community」入口。",
      "填写论坛名称（name）和描述（description）。",
      "按任务要求添加 sidebar 标签（tags/flairs）。",
      "提交创建，确认论坛主页已出现。",
    ],
    success: [
      "论坛名称与任务要求完全一致。",
      "Sidebar 包含任务要求的所有标签，顺序不限。",
    ],
    checks: [
      "论坛名称区分大小写，不要自动补全或更改。",
      "Sidebar 标签逐一核对列表，不要遗漏。",
    ],
    risk: "创建后论坛名称通常不可更改；提交前再次核对名称拼写。",
  },
  {
    id: "post-create",
    kind: "domain",
    title: "在 Subreddit 中发布新帖",
    keywords: "post, create, submit, ask, share, discuss, notice, review, recommend",
    modelTerms: ["post", "submit", "subreddit"],
    task: /\bpost\s+(?:a|my|in|to|about)\b|\bpost\s+(?:the\s+)?(?:question|review|notice|comment)\b|\bcreate\s+(?:a\s+)?(?:discussion\s+)?post\b|\bre-?post\b|\bask\s+for\s+(?:advice|(?:product\s+)?rec[oe]mmend)/i,
    evidence: /submit|post|thread|title|body|create|publish|发帖|发布|提交/i,
    coverage: /submit|post|thread|create|publish/i,
    steps: [
      "识别任务要求的目标 subreddit（明确指定或需根据主题推断）。",
      "进入该 subreddit，点击「New Post」或「Create Post」。",
      "填写标题（title）和正文（body）。如果是链接帖子，填写 URL。",
      "提交，确认帖子出现在 subreddit 页面。",
    ],
    success: [
      "帖子标题和正文与任务要求的文本一致。",
      "帖子发布在正确的 subreddit。",
    ],
    checks: [
      "如果任务要求「最合适的 subreddit」，根据主题选择最接近的已有论坛，不要自行创建。",
      "标题和正文中引号内的文字不要修改，原文照抄。",
      "图片帖子需选择 Link/Image 类型，不要发成文本帖子。",
    ],
    risk: "这是写操作；发帖内容来自任务要求的引号文本，不要自行改写。",
  },
  {
    id: "post-reply",
    kind: "domain",
    title: "回复帖子或评论",
    keywords: "reply, comment, respond, answer",
    modelTerms: ["reply", "comment", "respond"],
    task: /\breply\b.*\b(?:post|comment|thread)\b|\breply\s+to\b|\bcomment\b.*\b(?:post|thread)\b|\brespond\b|\banswer\b.*\b(?:post|thread)\b/i,
    evidence: /reply|comment|respond|answer|回复|评论/i,
    coverage: /reply|comment|respond/i,
    steps: [
      "导航到任务指定的帖子或评论（通过给定 URL 或描述定位）。",
      "找到任务要求的目标评论（如「第一条回复」「manager 发的评论」等）。",
      "点击 Reply，输入任务要求的回复文字，提交。",
      "确认回复已出现在帖子下方。",
    ],
    success: [
      "回复挂在正确的帖子或评论下。",
      "回复内容与任务要求的文字完全一致。",
    ],
    checks: [
      "区分「回复帖子」和「回复评论」：前者用主帖的 Reply 按钮，后者用具体评论的 Reply 按钮。",
      "如果评论被折叠，需先展开再回复。",
    ],
    risk: "这是写操作；回复后不可轻易撤回，务必核对目标和内容。",
  },
  {
    id: "vote",
    kind: "domain",
    title: "投票（点赞 / 踩）",
    keywords: "upvote, downvote, like, dislike, thumbs up, thumbs down",
    modelTerms: ["vote", "upvote", "downvote"],
    task: /\bupvote\s+(?:the\s+)?(?:newest|latest|top|\d+\s+)?\w*\s*post\b|\bdownvote\b|\bthumb[s]?\s+(?:up|down)\b|\blike\s+all\b|\bdislike\s+all\b|\blike\s+(?:all\s+)?submissions?\b|\bdislike\s+(?:all\s+)?submissions?\b|\blike\s+(?:the\s+)?(?:newest|latest|top|all)\s+post\b|\bdislike\s+(?:the\s+)?(?:newest|latest|top|all)\s+post\b/i,
    evidence: /vote|upvote|downvote|like|dislike|thumbs|投票|点赞|踩/i,
    coverage: /vote|like|dislike|thumbs/i,
    steps: [
      "导航到任务指定的 subreddit 或用户页面。",
      "找到目标帖子（通过排序「New」「Top」「Hot」定位）。",
      "对目标帖子点击对应的 upvote（向上箭头）或 downvote（向下箭头）。",
      "如果任务要求对多个帖子操作，逐一处理并在每次操作后确认图标状态变化。",
    ],
    success: [
      "目标帖子的 upvote/downvote 按钮显示为激活状态。",
      "操作帖子数量与任务要求一致。",
    ],
    checks: [
      "注意 Postmill 中点赞图标是箭头，不是 heart。",
      "「Top N post ever」用 Top > All Time 排序，「newest」用 New 排序。",
      "用户页面的帖子排序可能与 subreddit 页面不同，核对帖子标题后再投票。",
    ],
    risk: "投票后再次点击同一按钮会取消投票；确认激活状态后不要重复点击。",
  },
  {
    id: "user-edit",
    kind: "domain",
    title: "编辑个人资料或自己的帖子",
    keywords: "bio, profile, edit my post, my bio",
    modelTerms: ["profile", "bio", "edit"],
    task: /\b(?:change|update|set|edit)\s+my\s+(?:reddit\s+)?bio\b|\bedit\s+my\s+post\b|\bedit\s+my\s+(?:post\s+)?on\b/i,
    evidence: /bio|profile|account|settings|edit|self|个人资料|简介|编辑/i,
    coverage: /bio|profile|settings|edit/i,
    steps: [
      "进入账户设置（Settings / Preferences / Edit Profile）。",
      "找到 Bio / About 字段，清除旧内容后填入任务要求的文字。",
      "保存，返回个人资料页确认显示更新后的内容。",
    ],
    success: ["个人资料页的 Bio 字段显示任务要求的文字，与输入一致。"],
    checks: [
      "Bio 更新保存后需刷新个人资料页确认持久化。",
      "编辑帖子时要找到「Edit Post」选项，不是「Reply」。",
      "「adding a line」指在现有正文末尾追加，不是替换整体内容。",
    ],
    risk: "这是写操作；bio 和帖子内容会对其他用户可见，修改后不能自动恢复。",
  },
  {
    id: "subscribe",
    kind: "domain",
    title: "订阅论坛或帖子",
    keywords: "subscribe, follow, join, thread",
    modelTerms: ["subscribe", "follow"],
    task: /\bsubscribe\b|\bfollow\s+(?:a\s+)?(?:forum|subreddit|thread|post)\b/i,
    evidence: /subscribe|follow|join|订阅|关注/i,
    coverage: /subscribe|follow/i,
    steps: [
      "进入任务指定的 subreddit，找到 trending / hot 帖子。",
      "打开帖子详情页。",
      "点击 Subscribe（订阅帖子通知）按钮。",
      "确认订阅状态变更（按钮文字变为 Subscribed 或 Unsubscribe）。",
    ],
    success: ["目标帖子或论坛的订阅状态已激活。"],
    checks: [
      "Postmill 中「trending」通常对应 Hot 排序。",
      "订阅按钮可能在侧边栏（订阅论坛）或帖子详情页（订阅帖子通知）。",
    ],
    risk: "订阅是轻量级操作，可随时取消；风险较低。",
  },
  {
    id: "read-post",
    kind: "core",
    backoff: true,
    title: "浏览、搜索与读取帖子内容",
    keywords: "browse, find, count, list, read, tell me, show me, top, most",
    modelTerms: ["read", "browse", "count", "find"],
    task: /\b(?:tell me|show me|find|list|count|read|get|return|how many|what|which|among the top)\b/i,
    evidence: /post|thread|comment|subreddit|forum|user|count|list|find|帖子|评论|用户/i,
    coverage: /post|thread|comment|subreddit|forum|user/i,
    steps: [
      "定位目标 subreddit 或用户资料页。",
      "按任务要求的排序方式（New / Hot / Top / Controversial）浏览帖子。",
      "如果需要进入帖子详情，点击标题进入，读取评论区数据。",
      "如需统计，遍历分页并去重；如需详情，记录帖子 URL、标题、正文。",
    ],
    success: [
      "结果来自正确的 subreddit、用户、排序和时间范围。",
      "统计数字已考虑分页（不止首屏）。",
    ],
    checks: [
      "「latest post」用 New 排序第一条；「top post ever」用 Top > All Time。",
      "评论的 downvote > upvote 需进入用户资料页逐条检查，不能从首屏推断。",
      "URL 从帖子详情页地址栏复制，不要用首页列表的截断链接。",
    ],
    risk: "不要把首屏当作完整列表；如任务要求 Top N，必须使用正确排序而非默认排序。",
  },
  {
    id: "other",
    kind: "core",
    fallback: true,
    title: "未归类任务",
    keywords: "未命中已有工作流的任务",
    task: /.*/,
    evidence: /./,
    coverage: null,
    steps: [
      "先把任务拆成「导航到正确页面」「读取所需内容」「执行写操作」三个阶段。",
      "从当前页面语义和快照中寻找最接近的已验证入口。",
      "每一步都验证可见结果。",
    ],
    success: ["完成任务要求，且没有执行未授权的写操作。"],
    risk: "此工作流证据较弱；不要把未验证的推断当成站点事实。",
  },
];
