// shopping_admin workflow definitions
// 目标站点：Magento Admin Panel（WebArena shopping_admin）
// 任务语料：184 条，均来自 shopping_admin 站点

export default [
  {
    id: "admin-report",
    kind: "domain",
    title: "销售报表与聚合统计",
    keywords: "best-selling, top product, revenue, sales, quarter, month, brand, SKU",
    modelTerms: ["report", "sales", "order", "product"],
    task: /best.?selling|top.?\d|revenue|total.*sold|items? sold|sales.*report|best.*brand|best.*product type/i,
    evidence: /report|dashboard|bestseller|sales|revenue|statistics|analytics|revenue|报表|统计/i,
    coverage: /report|dashboard|sales|revenue|statistics|analytics/i,
    steps: [
      "确认报表类型（商品/品牌/类别/时间段）和筛选维度。",
      "进入 Reports 菜单，选择对应子报表（Products/Bestsellers/Orders）。",
      "设置时间范围筛选，刷新报表。",
      "按照任务要求读取 Top-N 行的名称、数量或金额字段。",
    ],
    success: [
      "结果来自正确的时间范围和报表类型。",
      "Top-N 顺序与报表排序一致。",
    ],
    checks: [
      "时间筛选必须精确到任务要求的年份/季度/月份边界。",
      "注意区分 Bestsellers（按销量）和 Revenue（按金额）报表。",
      "Top-N 结果中并列时按报表显示顺序返回，不推断。",
    ],
    risk: "报表是只读视图，无副作用；但筛选条件错误会导致错误数据，必须二次核对时间范围。",
  },
  {
    id: "admin-product-edit",
    kind: "domain",
    title: "商品属性编辑与状态管理",
    keywords: "update, disable, enable, price, description, SKU, on-sale, status",
    modelTerms: ["product", "catalog", "edit"],
    task: /(?:reduce|increase)\s+(?:the\s+)?price|(?:disable|enable)\s+\w|mark\s+all\s+\w|(?:update|change|set)\s+(?:the\s+|all\s+)?(?:\w+\s+)*(?:price|description|stock|out.?of.?stock|status|on.?sale|attribute|SKU)|set.*on.?sale/i,
    evidence: /catalog|product.*edit|save.*product|product.*save|attribute|sku|enable|disable|price|description|商品|属性|编辑/i,
    coverage: /catalog|product|edit|attribute|sku|price|description/i,
    steps: [
      "在 Catalog > Products 中通过名称或 SKU 定位目标商品。",
      "进入编辑页，确认商品名称与任务一致。",
      "只修改任务要求的字段（价格/描述/状态/属性等）。",
      "点击 Save，确认成功提示。",
    ],
    success: [
      "保存后页面显示成功提示。",
      "修改只作用于目标商品的指定字段。",
    ],
    checks: [
      "修改前记录原始值以备核对。",
      "Enable/Disable 操作后在列表页确认状态列已变更。",
      "价格修改时注意任务是绝对值还是相对增减。",
    ],
    risk: "这是写操作；修改错误商品或字段不可自动恢复，必须严格核对商品名称。",
  },
  {
    id: "admin-order",
    kind: "domain",
    title: "后台订单查询与操作",
    keywords: "order, cancel, invoice, shipment, customer order, pending, processing",
    modelTerms: ["order", "invoice", "shipment"],
    task: /\bcancel\s+(?:the\s+)?order|order.*status|pending.*order|processing.*order|find.*order|order.*number|invoice|shipment|notify\s+\w+.*order|modify.*address.*order|order.*address|update\s+order\s+#?\d+|order\s+#?\d+.*tracking/i,
    evidence: /sales.*order|order.*grid|invoice|shipment|cancel|order.*id|订单/i,
    coverage: /sales|order|invoice|shipment|cancel/i,
    steps: [
      "进入 Sales > Orders，用订单号、客户名或状态筛选。",
      "确认订单号与任务一致后进入详情。",
      "读取或执行任务要求的操作（状态查询/取消/发货等）。",
      "操作后确认状态变更。",
    ],
    success: [
      "读取任务：返回订单详情中的指定字段。",
      "写操作：页面出现成功提示且订单状态已变更。",
    ],
    checks: [
      "取消订单前确认当前状态允许取消（Pending/Processing）。",
      "不要根据订单号猜测 URL，通过搜索界面定位。",
    ],
    risk: "取消订单不可逆，执行前必须二次确认订单号和任务授权。",
  },
  {
    id: "admin-customer",
    kind: "domain",
    title: "客户信息查询与管理",
    keywords: "customer, email, nickname, account, group, address",
    modelTerms: ["customer", "account"],
    task: /customer(?:\s+\w+){0,3}\s+(?:email|name|group|address|account)|(?:list|view|return|get)\s+(?:all\s+)?customers?(?:\s|$)|view.*details.*(?:all\s+)?customers?/i,
    evidence: /customers?|customer.*grid|customer.*account|email|nickname|客户/i,
    coverage: /customer|account|email|nickname/i,
    steps: [
      "进入 Customers > All Customers。",
      "按名称、邮箱或客户组筛选目标客户。",
      "进入客户详情读取任务要求的字段。",
    ],
    success: [
      "结果来自正确客户记录。",
      "字段值与页面显示一致。",
    ],
    checks: [
      "同名客户用邮箱区分。",
      "nickname 字段在账户信息标签页，不在列表页。",
    ],
    risk: "修改客户信息是写操作；只有任务明确授权时才提交。",
  },
  {
    id: "admin-review",
    kind: "domain",
    title: "商品评论查询与管理",
    keywords: "review, rating, stars, reviewer, comment, approve, delete review",
    modelTerms: ["review", "rating"],
    task: /(?:how many|total number of)\s+reviews?\b|(?:list|return|get)\s+(?:all\s+)?reviews?\b|(?<!number of )reviews?\s+(?:with|that|for|rating|on)|reviewer|rating.*star|star.*rating|(?:delete|approve)\s+(?:all\s+)?(?:\w+\s+)*reviews?|customer nickname.*(?:rating|review|star)|nickname.*who.*(?:gave|rated|reviewed)/i,
    evidence: /reviews?|rating|stars?|reviewer|comment|approve|评论|评分/i,
    coverage: /review|rating|comment/i,
    steps: [
      "进入 Marketing > User Content > Reviews。",
      "按商品名称、评分或状态筛选评论。",
      "读取评论者、评分、标题和内容，保持同一评论的字段对齐。",
      "如需审批或删除，确认操作只作用于目标评论。",
    ],
    success: [
      "结果来自正确商品的评论记录。",
      "评论者、评分、标题、内容属于同一条评论。",
    ],
    checks: [
      "按评分筛选时注意区间（≤3 stars vs 精确 3 stars）。",
      "分页时记录已处理页，防止重复计数。",
    ],
    risk: "删除评论不可恢复；审批操作改变评论可见性，必须有明确任务授权。",
  },
  {
    id: "read-content",
    kind: "core",
    backoff: true,
    title: "读取列表、详情与结构化数据",
    keywords: "get, return, list, show, summarize, how many, find, retrieve",
    modelTerms: ["record", "detail", "list", "table"],
    task: /\b(?:get|return|list|show|summarize|what(?:'s| is)|how many|find out|read|retrieve|give me)\b/i,
    evidence: /details?|information|more|next|previous|table|list|view|read|详情|列表/i,
    coverage: /details?|information|results?|list|report|dashboard|详情|结果/i,
    steps: [
      "确认目标记录、列表或时间范围。",
      "读取字段标签和一条完整记录，建立字段对应关系。",
      "需要统计时遍历分页并去重；需要详情时保持记录上下文。",
      "按任务要求的数据结构、类型和格式返回。",
    ],
    success: [
      "结果来自正确记录或完整结果集。",
      "字段名称、数据类型和输出格式符合任务要求。",
    ],
    risk: "不要把首屏当作完整列表；缺失值与零值必须区分。",
  },
  {
    id: "edit-submit",
    kind: "core",
    title: "创建、修改与提交",
    keywords: "create, add, edit, update, delete, upload, save, send, notify",
    modelTerms: ["create", "edit", "update", "delete", "form"],
    backoff: true,
    task: /\b(?:create|add|edit|update|change|delete|remove|submit|upload|send|subscribe|post|publish|save)\b/i,
    evidence: /create|add|edit|update|delete|remove|submit|upload|send|publish|save|创建|编辑|删除|保存/i,
    coverage: /create|edit|new|settings|form|创建|编辑|设置/i,
    steps: [
      "打开目标记录或创建表单，确认当前身份与对象。",
      "按标签定位字段并填写，只修改任务要求的内容。",
      "提交前复核目标、字段差异和副作用。",
      "提交后验证成功提示、回显值或新记录标识。",
    ],
    success: [
      "修改只作用于目标对象和指定字段。",
      "页面显示成功提示或可验证的新状态。",
    ],
    risk: "这是写操作；删除、发布等不可逆动作必须有明确任务授权。",
  },
  {
    id: "navigation",
    kind: "core",
    backoff: true,
    title: "页面导航",
    keywords: "go to, open, navigate, view, settings page",
    modelTerms: ["navigation"],
    task: /\b(?:open|go to|navigate|pull up)\b|\bview .*page\b|\bcurrent page\b/i,
    evidence: /menu|dashboard|settings|configuration|page|菜单|设置|页面/i,
    coverage: /menu|settings|configuration|page|菜单|设置/i,
    steps: [
      "从当前 URL 和标题确认起点。",
      "使用左侧导航菜单或顶部菜单逐级进入目标页面。",
      "每次导航后检查 URL、主标题或关键内容。",
    ],
    success: ["最终页面的 URL、主标题和任务目标一致。"],
    checks: [
      "Admin 菜单可能需要 hover 展开子菜单。",
      "结束前重新读取页面，确认最终 URL 和标题同时匹配任务。",
    ],
    risk: "遇到同名菜单项时先核对完整路径，不用坐标猜测。",
  },
  {
    id: "other",
    kind: "core",
    fallback: true,
    title: "未归类任务",
    keywords: "未命中已有工作流的任务",
    task: /.*/,
    evidence: /./,
    coverage: null,
    steps: [
      "先把任务拆成导航、读取和写入三个阶段。",
      "从当前页面语义和快照中寻找最接近的已验证入口。",
      "每一步都验证可见结果。",
    ],
    success: ["完成任务要求，且没有执行未授权的写操作。"],
    risk: "此工作流证据较弱；不要把未验证的推断当成站点事实。",
  },
];
